#!/bin/bash
# Source function library.
. /etc/init.d/functions

#funtionc for command
command () {

	echo $var >> /home/output.txt

}
var=$1
 
        case "$1" in
                start)
                	command
			;;
		stop)
		        command
			;;
                restart)
                        command
			;;
		*)
			echo $"Usage: $0 {start|stop|restart}"
   			exit 2
			;;
	esac

exit 0
